config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/get_analytics_data'
  resources :visits
  resources :views
  resources :points
  resources :tours
  resources :users
  root "dashboard#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/views/_form.html.erb
<%= form_with(model: view, local: true) do |form| %>
  <% if view.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(view.errors.count, "error") %> prohibited this view from being saved:</h2>

      <ul>
        <% view.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :integer %>
    <%= form.text_field :integer %>
  </div>

  <div class="field">
    <%= form.label :tour_id %>
    <%= form.text_field :tour_id %>
  </div>

  <div class="field">
    <%= form.label :integer %>
    <%= form.text_field :integer %>
  </div>

  <div class="field">
    <%= form.label :point_id %>
    <%= form.text_field :point_id %>
  </div>

  <div class="field">
    <%= form.label :integer %>
    <%= form.text_field :integer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/views/edit.html.erb
<h1>Editing View</h1>

<%= render 'form', view: @view %>

<%= link_to 'Show', @view %> |
<%= link_to 'Back', views_path %>

app/views/views/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Views</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>User</th>
      <th>Integer</th>
      <th>Tour</th>
      <th>Integer</th>
      <th>Point</th>
      <th>Integer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @views.each do |view| %>
      <tr>
        <td><%= view.latitude %></td>
        <td><%= view.longitude %></td>
        <td><%= view.user_id %></td>
        <td><%= view.integer %></td>
        <td><%= view.tour_id %></td>
        <td><%= view.integer %></td>
        <td><%= view.point_id %></td>
        <td><%= view.integer %></td>
        <td><%= link_to 'Show', view %></td>
        <td><%= link_to 'Edit', edit_view_path(view) %></td>
        <td><%= link_to 'Destroy', view, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New View', new_view_path %>

app/views/views/new.html.erb
<h1>New View</h1>

<%= render 'form', view: @view %>

<%= link_to 'Back', views_path %>

app/views/views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @view.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @view.longitude %>
</p>

<p>
  <strong>User:</strong>
  <%= @view.user_id %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @view.integer %>
</p>

<p>
  <strong>Tour:</strong>
  <%= @view.tour_id %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @view.integer %>
</p>

<p>
  <strong>Point:</strong>
  <%= @view.point_id %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @view.integer %>
</p>

<%= link_to 'Edit', edit_view_path(@view) %> |
<%= link_to 'Back', views_path %>